### ISSUE TITLE
Test should use strategy.estimatedTotalAssets() instead of token.balanceOf(new_strategy.address) 

### ISSUE THREAD

**Issue by steffenix** [yearn/brownie-strategy-mix#30]
I think the testing code should be updated to facilitate the usage.
All the tests now are doing some asserts on `token.balanceOf(new_strategy.address) `

I suggest using `strategy.estimatedTotalAssets()` combined with `pytest.approx`

@fubuloubu toughts?

**Comment by fubuloubu** [comment]
Could you point to a concrete example in the tests? Overall, it sounds like a good idea though

**Comment by steffenix** [comment]
That issue came to me while I tried to write a strategy using the mix and when I realized that harvest will reinvest all the funds and the strategy will be left with nothing.
For example: https://github.com/iearn-finance/brownie-strategy-mix/blob/master/tests/test_operation.py#L13

**Comment by fubuloubu** [comment]
> That issue came to me while I tried to write a strategy using the mix and when I realized that harvest will reinvest all the funds and the strategy will be left with nothing.
> For example: https://github.com/iearn-finance/brownie-strategy-mix/blob/master/tests/test_operation.py#L13

Can you write up a sketch of what the change might look like? (or create a PR)

**Comment by steffenix** [comment]
Will write the PR
