### ISSUE TITLE
Add support for solidity 0.8 to sync with vaults PR

### ISSUE THREAD

**Issue by storming0x** [yearn/brownie-strategy-mix#34]
Should sync with vault PRs:

https://github.com/yearn/yearn-vaults/pull/244

NOTE: additional work is to create tags for previous 0.3.x releases to sync to vaults since we have to support all vaults across 0.3.x spectrum as well. Strategist should be able to switch tags to target as specific version using this repo.

**Comment by fubuloubu** [comment]
hmm, it might be nice to have a few branches for our major supported versions, with the latest being default. but this is an interesting issue.

**Comment by steffenix** [comment]
I can do it

**Comment by fubuloubu** [comment]
now that the 0.8.x is tagged, it should be possible to do this on a new branch

**Comment by steffenix** [comment]
https://github.com/yearn/brownie-strategy-mix/pull/36
