### ISSUE TITLE
add matching tags for releases based of yearn vaults repo

### ISSUE THREAD

**Issue by dougstorm** [yearn/brownie-strategy-mix#50]
Strategist need to target live vaults with different versions, e.g: 0.3.0, 0.3.5 0.4.2

We need to add matching tags version like v0.3.0 that strategist forking this repo can quickly
build the strategy with all test working on them as expected.

v0.3.0 in brownie mix should point to v0.3.0-1 in yearn-vaults to make the version simpler and avoid anyone deploying new strategies without health checks.

All code needs to be adjusted so its compatible with each vault version release.

Important releases to have matching tags for:

v0.3.0
v0.3.2
v0.3.3
v0.3.5
v0.4.2

(rest are not as critical since we don't have live vaults for those)

**Comment by steffenix** [comment]
https://github.com/yearn/brownie-strategy-mix/releases
