### ISSUE TITLE
Import deploy script from Yearn-Vaults

### ISSUE THREAD

**Issue by GalloDaSballo** [yearn/brownie-strategy-mix#54]
https://github.com/yearn/brownie-strategy-mix/blob/cdc942e8781d545b5866aeb4dac2adb8157e0402/scripts/deploy.py#L42

I'm looking into ways to import the deploy script from Yearn-Vaults into the Strategy Mix, I can import contracts but I can't find a way to import scripts.

Can you give me an intuition for how to make that work?

I'd be happy to add this functionality if you can point me in the right direction

**Comment by fubuloubu** [comment]
So, `~/.brownie/packages/<org>/<project>@<version>` is where Brownie stores the entire checked out repository, including scripts. There's a way to get the package location from Brownie, then just cd to that dir to execute the script, and cd back.

**Comment by GalloDaSballo** [comment]
Right, I can get the path similarly to how you import the `Vault` Artifact:
```python
    path_for_script = Path.home() / ".brownie" / "packages" / config["dependencies"][0] / "scripts"
    path_to_script = Path.home() / ".brownie" / "packages" / config["dependencies"][0] / "scripts" / "deploy.py"
```

I can then cd and try to run the script
```python
    ## Cd into it
    os.chdir(path_for_script.as_posix())
    ## Run with brownie there
    x = run(path_to_script.as_posix())
```

However I think I'm getting "sandboxed" and brownie doesn't let me load the script (see below)

<img width="1144" alt="Screenshot 2021-07-12 at 20 50 48" src="https://user-images.githubusercontent.com/13383782/125340513-d7117100-e352-11eb-91f5-a3289b4a73ba.png">
```python
ModuleNotFoundError: No module named 'Users.entreprenerd.'
```

What else could I try?

**Comment by GalloDaSballo** [comment]
I get a similar output `frozen` and `No module named \'Users.entreprenerd.` even by using:

```python
    process = subprocess.Popen(['brownie', 'run', 'deploy.py'],
                     stdout=subprocess.PIPE, 
                     stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()
    print(stdout)
    print(stderr)
```
and
```python
    stream = os.popen('brownie run deploy.py')
```

**Comment by fubuloubu** [comment]
> Right, I can get the path similarly to how you import the `Vault` Artifact:
> 
> ```python
>     path_for_script = Path.home() / ".brownie" / "packages" / config["dependencies"][0] / "scripts"
>     path_to_script = Path.home() / ".brownie" / "packages" / config["dependencies"][0] / "scripts" / "deploy.py"
> ```
> 
> I can then cd and try to run the script
> 
> ```python
>     ## Cd into it
>     os.chdir(path_for_script.as_posix())
>     ## Run with brownie there
>     x = run(path_to_script.as_posix())
> ```
> 
> However I think I'm getting "sandboxed" and brownie doesn't let me load the script (see below)
> 
> <img alt="Screenshot 2021-07-12 at 20 50 48" width="1144" src="https://user-images.githubusercontent.com/13383782/125340513-d7117100-e352-11eb-91f5-a3289b4a73ba.png">
> 
> ```
> ModuleNotFoundError: No module named 'Users.entreprenerd.'
> ```
> 
> What else could I try?

This bug sometimes happens if you try to use importlib to run a file as a module, but it's not located in a module directory.

You can fix it be appending it's parent directory to the `sys.path` list

**Comment by GalloDaSballo** [comment]
I've followed your advice and appended to `sys.path`

Code: https://github.com/GalloDaSballo/yearn-vaults/blob/7a2697693d76863fe1658bcb67e51e073a2ce932/scripts/deploy.py#L39

And the path is being added (temporarily) to it

However I'm still getting the same error
<img width="606" alt="Screenshot 2021-07-13 at 01 44 23" src="https://user-images.githubusercontent.com/13383782/125369095-db9e4f80-e37b-11eb-8a9e-45fdb1cee03d.png">

What else can I try?

**Comment by fubuloubu** [comment]
you shouldn't have to cd now that it's on your path

**Comment by GalloDaSballo** [comment]
I tried removing that from my path, but I still get frozen.

I'm running the deploy script with `brownie run deploy`

What else could I try?

**Comment by fubuloubu** [comment]
> What else could I try?

You can call scripts as paths as well, this might work:
```bash
$ brownie run ~/.brownie/packages/yearn/yearn-vaults@0.4.2/scripts/deploy.py
```
