### ISSUE TITLE
Accessing Vault via local ABI does not work

### ISSUE THREAD

**Issue by sjkelleyjr** [yearn/brownie-strategy-mix#78]
I just did a fresh clone of this repo and followed the README.  [This step doesn't work for me](https://github.com/yearn/brownie-strategy-mix/blob/master/README.md?plain=1#L73) and [I had to use these steps instead](https://github.com/yearn/brownie-strategy-mix/blob/master/README.md?plain=1#L62).  If it helps, the error I received was:

```
>>> vault.addStrategy(strategy, 1000, 0, 2 ** 256 - 1, 1_000, {"from": gov})
  File "<console>", line 1, in <module>
  File "brownie/network/contract.py", line 832, in __getattribute__
    raise AttributeError(f"Contract '{self._name}' object has no attribute '{name}'")
AttributeError: Contract 'VaultAPI' object has no attribute 'addStrategy'
```

when trying to add the strategy using the local ABIs.

**Comment by sjkelleyjr** [comment]
[same as this issue.](https://github.com/yearn/brownie-strategy-mix/issues/69#issue-1052824076)  Should I submit a PR removing this from the README?

**Comment by poolpitako** [comment]
@pandadefi ^^

**Comment by pandadefi** [comment]
Have you used export `ETHERSCAN_TOKEN=YourApiToken` with a valid etherscan token?

**Comment by pandadefi** [comment]
@sjkelleyjr can you have a look at the PR and try the new steps?

**Comment by sjkelleyjr** [comment]
@pandadefi that still doesn't work for me (same issue).  I'm using the `.env` file for the api keys and brownie is clearly able to read this because my infura endpoint has the correct project ID (`ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie --fork https://mainnet.infura.io/v3/<API_KEY> --chainId 1`...)

I tried manually exporting the etherscan token via command line (`export ETHERSCAN_TOKEN...`) before running `brownie console`, that didn't work either.  Is there a way to set the variable after running `brownie console`?

**Comment by pandadefi** [comment]
What is the error you are getting?

**Comment by sjkelleyjr** [comment]
same error:

```
AttributeError: Contract 'VaultAPI' object has no attribute 'addStrategy'
```

**Comment by sjkelleyjr** [comment]
for reference, here are the steps after running `brownie console`, in case I'm missing something:

```
Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie --fork https://mainnet.infura.io/v3/acea58cc8d764421a1f58f3207e85b14 --chainId 1'...
Brownie environment is ready.
>>> from brownie import Contract
vault = Contract("0xdA816459F1AB5631232FE5e97a05BBBb94970c95")
token = Contract("0x6b175474e89094c44da98b954eedeac495271d0f")
gov = "ychad.eth"  # ENS for Yearn Governance Multisig
>>> strategy = Strategy.deploy(vault, {"from": accounts[0]})
Transaction sent: 0xac1dd9eade986774cb089fcd06ac6866549314a3d378fb876ab4dc93fd2feca3
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
  Strategy.constructor confirmed   Block: 13934166   Gas used: 2540922 (21.17%)
  Strategy deployed at: 0xE7eD6747FaC5360f88a2EFC03E00d25789F69291

>>> vault.addStrategy(strategy, 1000, 0, 2 ** 256 - 1, 1_000, {"from": gov})
  File "<console>", line 1, in <module>
  File "brownie/network/contract.py", line 832, in __getattribute__
    raise AttributeError(f"Contract '{self._name}' object has no attribute '{name}'")
AttributeError: Contract 'VaultAPI' object has no attribute 'addStrategy'
```

**Comment by pandadefi** [comment]
It seems you have some issues with brownie, make sure you are using the latest version and do not have any cache. `vault.addStrategy` should not use the VaultAPI ABI since it is fetched from etherscan.

**Comment by sjkelleyjr** [comment]
I upgraded to the latest brownie version (`Brownie v1.17.2 - Python development framework for Ethereum`) and recreated the directory from scratch using `brownie bake yearn-strategy`.  Same issue: `AttributeError: Contract 'VaultAPI' object has no attribute 'addStrategy'`.
