### ISSUE TITLE
README.md instructions for ganache are incorrect.

### ISSUE THREAD

**Issue by anticlimactic** [yearn/brownie-strategy-mix#81]
I tried following the instructions to install ganache at the url in the README: 

https://github.com/trufflesuite/ganache-cli

If you click on the link you'll see that it takes you to trufflesuite/ganache. I believe truffle consolidated their products.

If you install the package there, brownie will be unsuccessful in starting a node as the parameters have different names (i.e. instead of `chainId` it is now `chain.chainId` etc.

The package that yearn was referring to was this package, which has been deprecated in favor of the above package.

https://www.npmjs.com/package/ganache-cli

The quick fix is to change the link to this package, the longer fix would be to change things around to work with the newer package.

**Comment by anticlimactic** [comment]
I just realized that brownie recently upgraded to support >v.7 of truffle a few days ago (requires brownie v1.18 or higher) so it is fine now.

I am happy to close this for now. However, I think it might be worthwhile stating in the `README.md` that brownie may not necessarily support the latest version of ganache and that you should check which version you are installing if you wish to make getting set up to write strategies more streamlined.

**Comment by poolpitako** [comment]
@anticlimactic want to open a PR with a fix to the `README.md`?
